
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.wood_type]

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.ad_astra]
			aeronos = true
			strophar = true
			glacian = true

		[types.wood_type.hexerei]
			mahogany = true
			willow = true
			witch_hazel = true

		[types.wood_type.iceandfire]
			dreadwood = true

		[types.wood_type.spore]
			rotten = true

		[types.wood_type.domum_ornamentum]
			cactus = true
			cactus_extra = true

		[types.wood_type.vinery]
			dark_cherry = true

		[types.wood_type.meadow]
			pine = true

		[types.wood_type.unusual_prehistory]
			ginkgo = true
			lepidodendron = true

		[types.wood_type.gtceu]
			rubber = true

	[types.leaves_type]

		[types.leaves_type.ad_astra]
			glacian = true

		[types.leaves_type.hexerei]
			mahogany = true
			willow = true
			witch_hazel = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.vinery]
			grapevine = true
			dark_cherry = true
			apple = true

		[types.leaves_type.meadow]
			pine = true

		[types.leaves_type.unusual_prehistory]
			ginkgo = true
			golden_ginkgo = true
			lepidodendron = true

		[types.leaves_type.gtceu]
			rubber = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.handcrafted]
			counter = true
			corner_trim = true
			fancy_bed = true
			desk = true
			shelf = true
			nightstand = true
			cupboard = true
			dining_bench = true
			bench = true
			couch = true
			table = true
			chair = true
			drawer = true
			pillar_trim = true
			side_table = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.quark]
			hollow_log = true
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true
			vertical_slab = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

