
["World Generation"]
	#Enable generation of rocks
	enableRocks = false
	#Enable generation of twigs
	enableTwigs = true
	#Enable generation of fallen leaves
	enableFallenLeaves = false
	#Enable generation of bones
	enableBones = false
	#Enable generation of charred bones
	enableCharredBones = false
	#Enable generation of ice chunks
	enableIceChunks = false
	#Enable generation of pinecones
	enablePinecones = false
	#Enable generation of seashells
	enableSeashells = false
	#Enable generation of fallen trees
	enableFallenTrees = false
	#Enable generation of sea oats
	enableSeaOats = true
	#Enable generation of cattails
	enableCattails = true
	#Enable generation of beach grass
	enableBeachGrass = false
	#Enable generation of bark mushrooms
	enableBarkMushrooms = false
	#Enable generation of glowcap
	enableGlowcap = false
	#Enable generation of cindercane
	enableCindercane = true
	#Enable generation of nether nettles
	enableNetherNettles = true
	#Enable generation of short grass
	enableShortGrass = false
	#Enable generation of natural cobwebs
	enableNaturalCobwebs = false
	#Enable generation of small cacti
	enableSmallCacti = false
	#Enable generation of prickly bushes
	enablePricklyBush = true
	#Enable generation of reeds
	enableReeds = true
	#Enable generation of extra lilypads in lakes
	enableExtraLilypads = false
	#Enable generation of extra seagrass in lakes
	enableExtraSeagrass = true
	#Enable generation of extra grass in rivers
	enableExtraRiverGrass = true
	#Enable moss carpets in old growth taiga biomes
	enableMossCarpets = false
	#Enable of tide pools in stony shores
	enableTidePools = true
	#Enable cave roots
	enableCaveRoots = true
	#Enable better ruined nether portals
	enableBetterRuinedNetherPortals = false
	#Enable generation of icicles
	enableIcicles = true
	#Enable generation of sandy sprouts
	enableSandySprouts = true
	#Enable generation of dried beached kelp
	enableDriedBeachedKelp = true
	#Enable generation of glowing blue fungus
	enableGlowingBlueFungus = true
	#Enable generation of muddy bones
	enableMuddyBones = true
	#Enable generation of lotus ponds in cherry groves
	enableLotusPonds = true
	#Enable generation of pink lotuses in flower forests
	enableFloatingPinkLotus = true
	#Enable generation of hot springs
	enableHotSprings = true
	#Enable generation of bushes
	enableBushes = true
	#Enable generation of wildflowers
	enableWildflowers = true
	#Enable generation of slime nodules
	enableSlimeNodules = true
	#Enable generation of pink vines
	enablePinkVines = true
	#Enable generation of watergrass
	enableWatergrass = true
	#Enable generation of gravel pits
	enableGravelPits = true
	#Enable generation of gold pits
	enableGoldPits = true
	#Enable generation of beached kelp
	enableBeachedKelp = true

["Entity Options"]
	#Enable spawning of tropical fish in jungles
	enableJungleTropicalFish = true

["Misc Options"]
	#Enable replaceable groundcover behavior - i.e. makes it behave like tall grass when placing blocks
	replaceableGroundcover = true

